stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - shell
  script:
    - echo "Building the application..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
      - Dockerfile
      - docker-compose.yml
      - deploy.sh
    expire_in: 1 week
  only:
    - master

deploy-job:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Deploying the application..."
    - chmod +x deploy.sh
    - ./deploy.sh
  environment:
    name: production
  only:
    - master
    