version: '3.8'

services:

  # Spring Backend приложение
  backend:
    image: auto-backend:latest
    container_name: auto-backend
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
    ports:
      - "8080:8080"
    networks:
      - auto-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: