server:
  port: 8088
  servlet:
    context-path: /api

spring:

  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access=false:

    database: POSTGRESQL
    show-sql: true
    #     Hibernate ddl auto (create, create-drop, validate, update)
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://213.183.45.128:5432/auto
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: 1Jy6lXMld5+F2K8z7Bc8E3z6oKQPfsd7L3l7QG3BFAc=
  authorities:
    key: roles
  header:
    string: Authorization
  refresh:
    token:
      expiration: 7

minio:
  url: http://213.183.45.128:9000
  accessKey: admin
  secretKey: admin12345
  buckets:
    image: images-bucket
    reports: reports-bucket

admin:
  mail: ${ADMIN_MAIL}
  password: ${ADMIN_PASSWORD}


customs:
  base-clearance-fee: 3100
  base-util-fee: 20000
  etc-util-coeff-base: 1.0
  ctp-util-coeff-base: 1.2
  excise-rates:
    gasoline: 58
    diesel: 58
    electric: 0
    hybrid: 58
  recycling-factors:
    default:
      gasoline: 1.0
      diesel: 1.0
      electric: 0.3
      hybrid: 1.0
    adjustments:
      "5-7":
        gasoline: 0.26
        diesel: 0.26
        electric: 0.26
        hybrid: 0.26
  age-groups:
    overrides:
      "5-7":
        gasoline:
          rate-per-cc: 4.8
          min-duty: 0
        diesel:
          rate-per-cc: 5.0
          min-duty: 0
        electric:
          rate-per-cc: 0
          min-duty: 1000
        hybrid:
          rate-per-cc: 2.0
          min-duty: 2500